### ISSUE TITLE
Got an exception when running it

### ISSUE THREAD

**Issue by leungmanhin** [jerry40/guile-simple-zmq#1]
I got this exception when running it with the guile-kernel, how can I resolve it?

```
[E 14:54:14.507 NotebookApp] Uncaught exception GET /api/kernels/88822785-a4ce-449a-be23-51f96aba4fd3/channels?session_id=A4BB60C922174F8BADCE1090D300692B (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/88822785-a4ce-449a-be23-51f96aba4fd3/channels?session_id=A4BB60C922174F8BADCE1090D300692B', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8,zh-TW;q=0.6,zh;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': '4Y5RFYS8IM0Ch1upT+bs9A==', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36', 'Dnt': '1', 'Connection': 'Upgrade', 'Cookie': '_xsrf=2|8e100e73|135320b6af60d0b004764c7aab418ddc|1516680643; username-localhost-8888="2|1:0|10:1516690119|23:username-localhost-8888|44:NThiMTI2MTcyOWVlNDdmODliY2Y3ZDRjYjdlNDdjNTQ=|e5d9693dbec1f1f2db9177e4f5042e24bab160c4d09723e69f06ee21ee06e88f"', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1468, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 184, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/local/lib/python2.7/dist-packages/notebook/services/kernels/handlers.py", line 313, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/session.py", line 915, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message
```

Also, could you share the required configs and the steps of running it? Just want to make sure I'm doing it right.

**Comment by jerry40** [comment]
Hi! I'm preparing an instruction for guile-kernel, soon I will place it here.  Important note: messages signing isn't done yet , so you need to switch it off on jupyter-notebook side. To do so you need to find its config file (or create it in the .jupyter folder):
```
To create a jupyter_notebook_config.py file in the .jupyter directory, 
with all the defaults commented out, use the following command:

    $ jupyter notebook --generate-config
```

After this you need top open it (jupyter_notebook_config.py), find Session.key parameter, uncomment it and make it empty:
```
Session.key : CBytes
Default: b''

execution key, for signing messages.
```
and restart the kernel

**Comment by leungmanhin** [comment]
Yes cool, it works now, thanks!
